@startuml
[*] --> Form表示 : Form Load

state Form表示 {
    [*]  --> 停止
    停止 --> 停止
    停止 --> 起動モード選択
    起動モード選択 --> 起動モード選択
    起動モード選択 --> 通常モード
    起動モード選択 --> パラメーター変更モード
    起動モード選択 --> 店頭デモモード
    パラメーター変更モード --> パラメーター変更モード
    パラメーター変更モード --> 通常モード
    パラメーター変更モード --> 停止
    通常モード --> 通常モード
    通常モード --> 停止
    店頭デモモード --> 店頭デモモード
    店頭デモモード --> 通常モード
    店頭デモモード --> 停止
    通常モード --> エラーモード
    エラーモード --> 停止
    エラーモード --> エラーモード
}

Form表示 --> [*] : Form Close
@enduml